server:
  port: 8080

spring:
  application:
    name: gym-server  # 服务名称

  # ================================
  # 数据源配置
  # ================================
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:118.178.144.106}:3306/gym_database?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: gym_database
    password: 4waxiFiWAX2SSpZS

  # ================================
  # Redis配置
  # ================================
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    password: root123456

  # ================================
  # Nacos服务发现配置
  # ================================
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: gym-system
        group: DEFAULT_GROUP
        cluster-name: default
        metadata:
          version: 1.0.0
          zone: zone1

  #临时解决方案
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: wxinran543@gmail.com      # 替换为你的 Gmail 邮箱地址
    password: dlgyysvqolbcljep          # 替换为你的 Gmail 应用专用密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

jwt:
  secret: "YourJWTSecretKey"
  expiration: 86400000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gym-common.com.gym.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  locale: en

tencent:
  captcha:


google:
  clientId: "642557482063-q866pb3tlp0blvso126q2i2si40qn6oh.apps.googleusercontent.com"

# Elasticsearch 配置
elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: 9200
  scheme: http
  connection-timeout: 5000
  socket-timeout: 60000

# 健身房ES业务配置
gym:
  elasticsearch:
    # 是否启用ES功能
    enabled: true
    # 索引配置
    index:
      trainer:
        name: gym_trainers
        shards: 3
        replicas: 1
        refresh-interval: 1s
    # 数据同步配置
    sync:
      enabled: true
      batch-size: 100
      retry-times: 3
      # 增量同步间隔（分钟）
      incremental-interval: 5
      # 全量同步时间（cron表达式）
      full-sync-cron: "0 0 2 * * ?"

---
# ================================
# Docker环境配置
# ================================
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://118.178.144.106:3306/gym_database?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: gym_database
    password: 4waxiFiWAX2SSpZS
  redis:
    host: redis
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

# Elasticsearch Docker配置
elasticsearch:
  host: elasticsearch

#server:
#  port: 8080
#
#spring:
#  profiles:
#    active: dev
#  main:
#    allow-circular-references: true
#  datasource:
#    druid:
#      driver-class-name: ${sky.datasource.driver-class-name}
#      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${sky.datasource.username}
#      password: ${sky.datasource.password}

#sky:
#  jwt:
#    # 设置jwt签名加密时使用的秘钥
#    admin-secret-key: itcast
#    # 设置jwt过期时间
#    admin-ttl: 7200000
#    # 设置前端传递过来的令牌名称
#    admin-token-name: token
